### ISSUE TITLE
There are no free transfer ports at this moment, please try again later

### ISSUE THREAD

**Issue by hucongquan** [fast-data-transfer/fdt#46]
when I use fdt to transfer file in  *blocking* I/O mode, upload file from client to server , it always be ok. however, when I download file from server to client, first time success , after the second time, it always failed ,server will print "There are no free transfer ports at this moment, please try again later".If anyone knows the solution, please let me know.

1.Windows 7 professional
2.Qt 5.12.6
3.fdt 0.26.1 2017-08-08

[client_logger](https://github.com/fast-data-transfer/fdt/files/4720399/transfer_logger.txt)
[server_logger](https://github.com/fast-data-transfer/fdt/files/4720401/server_logger.txt)
[transfer.ELvWtI](https://github.com/fast-data-transfer/fdt/files/4720405/transfer.txt)

**Comment by hucongquan** [comment]
client_logger
[2020-06-02 18:35:15 周二]:fdt commad:Y:/transfer-mac/transfer/bin/debug/tool/bin/java-jar Y:/transfer-mac/transfer/bin/debug/tool/fdt.jar -notmp -noupdates -pull -p 42445 -r -c 172.21.100.231 -d / -fl C:/Users/peter_hu/AppData/Local/Temp/transfer.ItSpuO
[2020-06-02 18:35:16 周二]:onReadyReadStandardOutput:2020-06-02 18:35:16 信息 lia.util.net.copy.FDT main 

FDT [ 0.26.1-201708081830 ] STARTED ... 



[2020-06-02 18:35:16 周二]:onReadyReadStandardOutput:2020-06-02 18:35:16 信息 lia.util.net.common.Config <init> Using lia.util.net.copy.PosixFSFileChannelProviderFactory as FileChannelProviderFactory
2020-06-02 18:35:16 信息 lia.util.net.common.Config <init> FDT started in client mode
2020-06-02 18:35:16 信息 lia.util.net.copy.FDT main FDT uses *blocking* I/O mode.

[2020-06-02 18:35:17 周二]:onReadyReadStandardOutput:2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 1 ): PROTOCOL_VERSION msg: 0.26.1-2017-08-08
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 4 ): INIT_FDT_CONF msg: {-p=42445, -P=4, -limit=-1, -ka=120, -notmp=, -noupdates=, -r=, user.home=C:\Users\peter_hu, user.dir=Y:\transfer-mac\transfer\bin, user.name=peter_hu, path.separator=;, -ss=-1, file.separator=\, -fl=C:/Users/peter_hu/AppData/Local/Temp/transfer.ItSpuO, file.encoding=GBK, -c=172.21.100.231, -d=/, LastParams=[], -limitDelay=300, -pull=, -bs=1048576}

[2020-06-02 18:35:17 周二]:onReadyReadStandardOutput:2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 2 ): SESSION_ID msg: fc2f0c58-9031-4457-8f8b-d3fa4722aeea
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel initStreams NEW CONTROL stream for fc2f0c58-9031-4457-8f8b-d3fa4722aeea initialized 
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel initStreams App KeepAlive [ 120 second(s) ] enabled for control channel. Local FDTVersion [0.26.1-2017-08-08], Remote FDTVersion [0.26.1-2017-08-08]
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel$ControlChannelPingerTask <init> [ ControlChannelPingerTask ] initialized
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel sendTransferPortMessage [ ControlChannel ] [ sendTransferPortMessage ]
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 15 ): REMOTE_TRANSFER_PORT msg: rtp

[2020-06-02 18:35:18 周二]:onReadyReadStandardOutput:2020-06-02 18:35:18 信息 lia.util.net.common.Utils getFDTTransferPort Got transfer port: 172.21.100.231:43210

[2020-06-02 18:35:18 周二]:onReadyReadStandardOutput:2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 1 ): PROTOCOL_VERSION msg: 0.26.1-2017-08-08
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 4 ): INIT_FDT_CONF msg: {-p=42445, -P=4, -limit=-1, -ka=120, -notmp=, -noupdates=, -r=, user.home=C:\Users\peter_hu, user.dir=Y:\transfer-mac\transfer\bin, user.name=peter_hu, path.separator=;, -ss=-1, file.separator=\, -fl=C:/Users/peter_hu/AppData/Local/Temp/transfer.ItSpuO, file.encoding=GBK, -c=172.21.100.231, -d=/, LastParams=[], -limitDelay=300, -pull=, -bs=1048576}
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 2 ): SESSION_ID msg: fef2a65d-4b9e-4230-8910-f6e90686543a
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel initStreams NEW CONTROL stream for fef2a65d-4b9e-4230-8910-f6e90686543a initialized 
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel initStreams App KeepAlive [ 120 second(s) ] enabled for control channel. Local FDTVersion [0.26.1-2017-08-08], Remote FDTVersion [0.26.1-2017-08-08]
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel$ControlChannelPingerTask <init> [ ControlChannelPingerTask ] initialized

[2020-06-02 18:35:20 周二]:onReadyReadStandardOutput:Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: \tmp\fef2a65d-4b9e-4230-8910-f6e90686543a.log.lck
java.nio.file.NoSuchFileException: \tmp\fef2a65d-4b9e-4230-8910-f6e90686543a.log.lck
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(Unknown Source)
	at java.nio.channels.FileChannel.open(Unknown Source)
	at java.nio.channels.FileChannel.open(Unknown Source)
	at java.util.logging.FileHandler.openFiles(Unknown Source)
	at java.util.logging.FileHandler.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at java.util.logging.LogManager$5.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(Unknown Source)
	at java.util.logging.LogManager.initializeGlobalHandlers(Unknown Source)
	at java.util.logging.LogManager.access$1500(Unknown Source)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(Unknown Source)
	at java.util.logging.Logger.getHandlers(Unknown Source)
	at java.util.logging.Logger.log(Unknown Source)
	at java.util.logging.Logger.doLog(Unknown Source)
	at java.util.logging.Logger.log(Unknown Source)
	at lia.util.net.copy.transport.ControlChannel.sendMsgImpl(ControlChannel.java:447)
	at lia.util.net.copy.transport.ControlChannel.sendAllMsgs(ControlChannel.java:441)
	at lia.util.net.copy.transport.ControlChannel.run(ControlChannel.java:512)
	at java.lang.Thread.run(Unknown Source)
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 6 ): INIT_FDTSESSION_CONF msg: 
 destinationDir: /
 destinationIP: 
 destinationPort: 0
 sourceIP:  recursive: true dirOffset: null
 UUID[]: null
 fileList[]: [/filesystem/project/contenthub/3/reference_file/a2/85/a2851d12139d44539874386ad032e52e]
 remappedFileLists[]: [C:/Users/peter_hu/Desktop/contenthub/372M.mov]
 fileSizes[]: null
 lastModifTimes[]: null
2020-06-02 18:35:20 信息 lia.util.net.copy.transport.SpeedLimitManager addLimiter  Adding SpeedLimiterTask for lia.util.net.copy.transport.TCPSessionReader@11dd7672 delay: 300 ms

[2020-06-02 18:35:26 周二]:onReadyReadStandardOutput:2020-06-02 18:35:20 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 7 ): FINAL_FDTSESSION_CONF msg: [Ljava.util.UUID;@4f60fcc
2020-06-02 18:35:20 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 9 ): START_SESSION msg: 43210
2020-06-02 18:35:21 信息 lia.util.net.copy.transport.TCPTransportProvider tryToConnect Requested window size -1. Using window size: 8192
2020-06-02 18:35:22 信息 lia.util.net.copy.disk.DiskWriterTask run DiskWriterTask [ partitionID=0, writerID= 0, tid=13 ] since: Tue Jun 02 18:35:22 CST 2020 STARTED. Active = true
2020-06-02 18:35:22 信息 lia.util.net.copy.FDTSession finishFileSession /\C:/Users/peter_hu/Desktop/contenthub/372M.mov STATUS: OK
2020-06-02 18:35:22 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 10 ): END_SESSION msg: null

[2020-06-02 18:35:29 周二]:onReadyReadStandardOutput:2020-06-02 18:35:26 信息 lia.util.net.copy.monitoring.ConsoleReportingTask reportStatus Net In: 3.356 Mb/s	Avg: 3.356 Mb/s
2020-06-02 18:35:27 信息 lia.util.net.copy.FDTWriterSession finalCleanup DATE=20200602183527.018000 HOST=ws312-PC PROG=fdt START=20200602183518.884000 BUFFER=0 BLOCK=1048576 NBYTES=2097152 STREAMS=4 DEST=[172.21.100.231] TYPE=STOR CODE=226


FDTWriterSession ( fef2a65d-4b9e-4230-8910-f6e90686543a ) final stats:
 Started: Tue Jun 02 18:35:18 CST 2020
 Ended:   Tue Jun 02 18:35:27 CST 2020
 Transfer period:   08s
 TotalBytes: 2097152
 TotalNetworkBytes: 2097152
 Exit Status: OK

2020-06-02 18:35:27 信息 lia.util.net.copy.FDTWriterSession doPostProcessing [ FDTWriterSession ] Post Processing started
2020-06-02 18:35:27 信息 lia.util.net.copy.FDTWriterSession doPostProcessing [ FDTWriterSession ] No post processing filters defined/processed.
2020-06-02 18:35:27 信息 lia.util.net.copy.transport.ControlChannel run  ControlThread for ( fef2a65d-4b9e-4230-8910-f6e90686543a ) /172.21.100.231:43210 FINISHED
2020-06-02 18:35:28 信息 lia.util.net.copy.FDT doWork  [ Tue Jun 02 18:35:28 CST 2020 ] - GracefulStopper hook started ... Waiting for the cleanup to finish
2020-06-02 18:35:28 信息 lia.util.net.copy.FDT doWork  [ Tue Jun 02 18:35:28 CST 2020 ]  - GracefulStopper hook finished!
2020-06-02 18:35:28 信息 lia.util.net.copy.FDT doWork 
 [ Tue Jun 02 18:35:28 CST 2020 ]  FDT Session finished OK.


[2020-06-02 18:36:45 周二]:fdt commad:Y:/transfer-mac/transfer/bin/debug/tool/bin/java-jar Y:/transfer-mac/transfer/bin/debug/tool/fdt.jar -notmp -noupdates -pull -p 42445 -r -c 172.21.100.231 -d / -fl C:/Users/peter_hu/AppData/Local/Temp/transfer.ELvWtI
[2020-06-02 18:36:47 周二]:onReadyReadStandardOutput:2020-06-02 18:36:47 信息 lia.util.net.copy.FDT main 

FDT [ 0.26.1-201708081830 ] STARTED ... 


2020-06-02 18:36:47 信息 lia.util.net.common.Config <init> Using lia.util.net.copy.PosixFSFileChannelProviderFactory as FileChannelProviderFactory
2020-06-02 18:36:47 信息 lia.util.net.common.Config <init> FDT started in client mode
2020-06-02 18:36:47 信息 lia.util.net.copy.FDT main FDT uses *blocking* I/O mode.
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 1 ): PROTOCOL_VERSION msg: 0.26.1-2017-08-08
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 4 ): INIT_FDT_CONF msg: {-p=42445, -P=4, -limit=-1, -ka=120, -notmp=, -noupdates=, -r=, user.home=C:\Users\peter_hu, user.dir=Y:\transfer-mac\transfer\bin, user.name=peter_hu, path.separator=;, -ss=-1, file.separator=\, -fl=C:/Users/peter_hu/AppData/Local/Temp/transfer.ELvWtI, file.encoding=GBK, -c=172.21.100.231, -d=/, LastParams=[], -limitDelay=300, -pull=, -bs=1048576}

[2020-06-02 18:36:48 周二]:onReadyReadStandardOutput:2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 2 ): SESSION_ID msg: 38fb0771-ab2c-43d0-9e18-efbc8b800cc0
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel initStreams NEW CONTROL stream for 38fb0771-ab2c-43d0-9e18-efbc8b800cc0 initialized 
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel initStreams App KeepAlive [ 120 second(s) ] enabled for control channel. Local FDTVersion [0.26.1-2017-08-08], Remote FDTVersion [0.26.1-2017-08-08]
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel$ControlChannelPingerTask <init> [ ControlChannelPingerTask ] initialized
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel sendTransferPortMessage [ ControlChannel ] [ sendTransferPortMessage ]
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 15 ): REMOTE_TRANSFER_PORT msg: rtp

[2020-06-02 18:36:49 周二]:onReadyReadStandardOutput:2020-06-02 18:36:49 信息 lia.util.net.common.Utils getFDTTransferPort Got transfer port: 172.21.100.231:-1
2020-06-02 18:36:49 警告 lia.util.net.copy.FDTSessionManager addFDTClientSession Got exception initiation Session/RemoteConn 
java.lang.Exception: java.lang.IllegalArgumentException: port out of range:-1
	at lia.util.net.copy.transport.ControlChannel.<init>(ControlChannel.java:109)
	at lia.util.net.copy.transport.ControlChannel.<init>(ControlChannel.java:65)
	at lia.util.net.copy.FDTSession.<init>(FDTSession.java:131)
	at lia.util.net.copy.FDTWriterSession.<init>(FDTWriterSession.java:48)
	at lia.util.net.copy.FDTSessionManager.addFDTClientSession(FDTSessionManager.java:107)
	at lia.util.net.copy.FDT.<init>(FDT.java:91)
	at lia.util.net.copy.FDT.main(FDT.java:467)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at lia.util.net.copy.FDTMain.main(FDTMain.java:55)
Caused by: java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(Unknown Source)
	at java.net.InetSocketAddress.<init>(Unknown Source)
	at lia.util.net.copy.transport.ControlChannel.<init>(ControlChannel.java:89)
	... 11 more

2020-06-02 18:36:49 警告 lia.util.net.copy.FDT main Failed to instantiate FDT
java.lang.Exception: java.lang.Exception: java.lang.IllegalArgumentException: port out of range:-1
	at lia.util.net.copy.FDTSessionManager.addFDTClientSession(FDTSessionManager.java:124)
	at lia.util.net.copy.FDT.<init>(FDT.java:91)
	at lia.util.net.copy.FDT.main(FDT.java:467)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at lia.util.net.copy.FDTMain.main(FDTMain.java:55)
Caused by: java.lang.Exception: java.lang.IllegalArgumentException: port out of range:-1
	at lia.util.net.copy.transport.ControlChannel.<init>(ControlChannel.java:109)
	at lia.util.net.copy.transport.ControlChannel.<init>(ControlChannel.java:65)
	at lia.util.net.copy.FDTSession.<init>(FDTSession.java:131)
	at lia.util.net.copy.FDTWriterSession.<init>(FDTWriterSession.java:48)
	at lia.util.net.copy.FDTSessionManager.addFDTClientSession(FDTSessionManager.java:107)
	... 7 more
Caused by: java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(Unknown Source)
	at java.net.InetSocketAddress.<init>(Unknown Source)
	at lia.util.net.copy.transport.ControlChannel.<init>(ControlChannel.java:89)
	... 11 more

**Comment by hucongquan** [comment]
-fl filelist

/filesystem/project/contenthub/3/reference_file/00/d0/00d0eccecc014296912e2d14622bc109 / C:/Users/peter_hu/Desktop/contenthub/2G.mov

**Comment by hucongquan** [comment]
server_logger

[root@contenthub fdtServer]# java -jar fdt.jar -p 42445
2020-06-02 18:33:50 信息 lia.util.net.copy.FDT main 

FDT [ 0.26.1-201708081830 ] STARTED ... 


2020-06-02 18:33:50 信息 lia.util.net.common.Config <init> Using lia.util.net.copy.PosixFSFileChannelProviderFactory as FileChannelProviderFactory
2020-06-02 18:33:50 信息 lia.util.net.common.Config <init> FDT started in server mode
2020-06-02 18:33:50 信息 lia.util.net.copy.FDT main FDT uses *blocking* I/O mode.
READY
2020-06-02 18:33:50 信息 lia.util.net.copy.FDTServer doWork FDTServer start listening on port: 42445
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 1 ): PROTOCOL_VERSION msg: 0.26.1-2017-08-08
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 4 ): INIT_FDT_CONF msg: {-p=42445, -P=4, -limit=-1, -ka=120, user.home=/root, user.dir=/server/fdtServer, user.name=root, path.separator=:, -ss=-1, file.separator=/, file.encoding=UTF-8, LastParams=[], -limitDelay=300, -bs=1048576}
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel initStreams NEW CONTROL stream for fc2f0c58-9031-4457-8f8b-d3fa4722aeea initialized 
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel initStreams App KeepAlive [ 120 second(s) ] enabled for control channel. Local FDTVersion [0.26.1-2017-08-08], Remote FDTVersion [0.26.1-2017-08-08]
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel$ControlChannelPingerTask <init> [ ControlChannelPingerTask ] initialized
2020-06-02 18:35:17 信息 lia.util.net.copy.FDTSession handleGetRemoteTransferPortMessage [ FDTSession ] [ handleGetRemoteTransferPortMessage ( rtp )
Took new remote transfer port 43210
2020-06-02 18:35:17 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 15 ): REMOTE_TRANSFER_PORT msg: 43210
2020-06-02 18:35:18 信息 lia.util.net.copy.FDTSession handleGetRemoteTransferPortMessage [ FDTSession ] [ handleGetRemoteTransferPortMessage ( closing session )
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 1 ): PROTOCOL_VERSION msg: 0.26.1-2017-08-08
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 4 ): INIT_FDT_CONF msg: {-p=42445, -P=4, -limit=-1, -ka=120, user.home=/root, user.dir=/server/fdtServer, user.name=root, path.separator=:, -ss=-1, file.separator=/, file.encoding=UTF-8, LastParams=[], -limitDelay=300, -bs=1048576}
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel initStreams NEW CONTROL stream for fef2a65d-4b9e-4230-8910-f6e90686543a initialized 
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel initStreams App KeepAlive [ 120 second(s) ] enabled for control channel. Local FDTVersion [0.26.1-2017-08-08], Remote FDTVersion [0.26.1-2017-08-08]
2020-06-02 18:35:18 信息 lia.util.net.copy.transport.ControlChannel$ControlChannelPingerTask <init> [ ControlChannelPingerTask ] initialized
2020-06-02 18:35:18 信息 lia.util.net.copy.FDTReaderSession internalInit [ FDTReaderSession ] No pre processing filters defined/processed.
2020-06-02 18:35:19 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 7 ): FINAL_FDTSESSION_CONF msg: 
 destinationDir: /
 destinationIP: 
 destinationPort: 0
 sourceIP:  recursive: true dirOffset: null
 UUID[]: [ac96a137-170f-4e5a-a57e-3e9e5fcd5509]
 fileList[]: [/filesystem/project/contenthub/3/reference_file/a2/85/a2851d12139d44539874386ad032e52e]
 remappedFileLists[]: [C:/Users/peter_hu/Desktop/contenthub/372M.mov]
 fileSizes[]: [2097152]
 lastModifTimes[]: [1591084446000]
2020-06-02 18:35:20 信息 lia.util.net.copy.transport.SpeedLimitManager addLimiter  Adding SpeedLimiterTask for lia.util.net.copy.transport.TCPSessionWriter@5f30f44b delay: 300 ms
2020-06-02 18:35:21 信息 lia.util.net.copy.FDTReaderSession startReading  Started DiskReaderTasks for the following partions [ 64770 ] for FDTSession: fef2a65d-4b9e-4230-8910-f6e90686543a
2020-06-02 18:35:21 信息 lia.util.net.copy.FDTSession finishFileSession /filesystem/project/contenthub/3/reference_file/a2/85/a2851d12139d44539874386ad032e52e STATUS: OK
2020-06-02 18:35:21 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 9 ): START_SESSION msg: 0
2020-06-02 18:35:21 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 10 ): END_SESSION msg: {}
2020-06-02 18:35:22 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 10 ): END_SESSION msg: {}
2020-06-02 18:35:23 信息 lia.util.net.copy.FDTReaderSession handleEndFDTSession [ FDTReaderSession ] Remote FDTWriterSession for session [ fef2a65d-4b9e-4230-8910-f6e90686543a ] finished OK!
2020-06-02 18:35:26 信息 lia.util.net.copy.FDTReaderSession finalCleanup DATE=20200602183526.011000 HOST=contenthub.42443 PROG=fdt START=20200602183518.925000 BUFFER=0 BLOCK=1048576 NBYTES=2097152 STREAMS=4 DEST=[172.21.100.112] TYPE=RETR CODE=226
2020-06-02 18:35:26 信息 lia.util.net.copy.FDTReaderSession finalCleanup 

FDTReaderSession ( fef2a65d-4b9e-4230-8910-f6e90686543a ) final stats:
 Started: Tue Jun 02 18:35:18 CST 2020
 Ended:   Tue Jun 02 18:35:26 CST 2020
 Transfer period:   07s
 TotalBytes: 2097152
 TotalNetworkBytes: 2097152
 Exit Status: OK



FDTReaderSession ( fef2a65d-4b9e-4230-8910-f6e90686543a ) final stats:
 Started: Tue Jun 02 18:35:18 CST 2020
 Ended:   Tue Jun 02 18:35:26 CST 2020
 Transfer period:   07s
 TotalBytes: 2097152
 TotalNetworkBytes: 2097152
 Exit Status: OK

2020-06-02 18:35:26 信息 lia.util.net.copy.FDTReaderSession doPostProcessing [ FDTReaderSession ] Post Processing started
2020-06-02 18:35:26 信息 lia.util.net.copy.FDTReaderSession doPostProcessing [ FDTReaderSession ] No post processing filters defined/processed.
2020-06-02 18:35:28 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 12 ): END_SESSION_FIN2 msg: nullStack trace unavailable
2020-06-02 18:35:28 信息 lia.util.net.copy.transport.ControlChannel run  ControlThread for ( fc2f0c58-9031-4457-8f8b-d3fa4722aeea ) /172.21.100.112:51658 FINISHED
2020-06-02 18:35:28 信息 lia.util.net.copy.transport.ControlChannel run  ControlThread for ( fef2a65d-4b9e-4230-8910-f6e90686543a ) /172.21.100.112:51659 FINISHED
2020-06-02 18:35:28 信息 lia.util.net.copy.FDTReaderSession internalClose 
The FDTReaderSession ( fc2f0c58-9031-4457-8f8b-d3fa4722aeea ) finished with error(s). downMsg: ControlChannel is down downCause:
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:206)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2640)
	at java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:2947)
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2957)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1539)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at lia.util.net.copy.transport.ControlChannel.run(ControlChannel.java:513)
	at java.lang.Thread.run(Thread.java:748)

2020-06-02 18:35:28 信息 lia.util.net.copy.FDTReaderSession finalCleanup DATE=20200602183528.653000 HOST=contenthub.42443 PROG=fdt START=20200602183517.606000 BUFFER=0 BLOCK=1048576 NBYTES=0 STREAMS=0 DEST=[172.21.100.112] TYPE=RETR CODE=426
2020-06-02 18:35:28 信息 lia.util.net.copy.FDTReaderSession finalCleanup 

FDTReaderSession ( fc2f0c58-9031-4457-8f8b-d3fa4722aeea ) final stats:
 Started: Tue Jun 02 18:35:17 CST 2020
 Ended:   Tue Jun 02 18:35:28 CST 2020
 Transfer period:   11s
 TotalBytes: 0
 TotalNetworkBytes: 0
 Exit Status: Not OK



FDTReaderSession ( fc2f0c58-9031-4457-8f8b-d3fa4722aeea ) final stats:
 Started: Tue Jun 02 18:35:17 CST 2020
 Ended:   Tue Jun 02 18:35:28 CST 2020
 Transfer period:   11s
 TotalBytes: 0
 TotalNetworkBytes: 0
 Exit Status: Not OK

2020-06-02 18:35:28 信息 lia.util.net.copy.FDTReaderSession doPostProcessing [ FDTReaderSession ] Post Processing started
2020-06-02 18:35:28 信息 lia.util.net.copy.FDTReaderSession doPostProcessing [ FDTReaderSession ] No post processing filters defined/processed.
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 1 ): PROTOCOL_VERSION msg: 0.26.1-2017-08-08
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 4 ): INIT_FDT_CONF msg: {-p=42445, -P=4, -limit=-1, -ka=120, user.home=/root, user.dir=/server/fdtServer, user.name=root, path.separator=:, -ss=-1, file.separator=/, file.encoding=UTF-8, LastParams=[], -limitDelay=300, -bs=1048576}
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel initStreams NEW CONTROL stream for 38fb0771-ab2c-43d0-9e18-efbc8b800cc0 initialized 
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel initStreams App KeepAlive [ 120 second(s) ] enabled for control channel. Local FDTVersion [0.26.1-2017-08-08], Remote FDTVersion [0.26.1-2017-08-08]
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel$ControlChannelPingerTask <init> [ ControlChannelPingerTask ] initialized
2020-06-02 18:36:47 信息 lia.util.net.copy.FDTSession handleGetRemoteTransferPortMessage [ FDTSession ] [ handleGetRemoteTransferPortMessage ( rtp )
2020-06-02 18:36:47 信息 lia.util.net.copy.transport.ControlChannel sendMsgImpl  [ ControlChannel ] sending message tag ( 15 ): REMOTE_TRANSFER_PORT msg: -1
2020-06-02 18:36:48 警告 lia.util.net.copy.FDTSession handleGetRemoteTransferPortMessage There are no free transfer ports at this moment, please try again later
2020-06-02 18:36:49 信息 lia.util.net.copy.transport.ControlChannel run  ControlThread for ( 38fb0771-ab2c-43d0-9e18-efbc8b800cc0 ) /172.21.100.112:51722 FINISHED

**Comment by hucongquan** [comment]
client fdt command like this:
`java -jar Y:/transfer-mac/transfer/bin/debug/tool/fdt.jar -notmp -noupdates -pull -p 42445 -r -c 172.21.100.231 -d / -fl C:/Users/peter_hu/AppData/Local/Temp/transfer.ELvWtI`

**Comment by hucongquan** [comment]
@earlephilhower @juztas @nlmills @fixy  Please take a look at this problem for me, thank you~

**Comment by fixy** [comment]
Hello, i will try to reproduce your issue today, seems transfer port is not returned back to transfer ports pool.

**Comment by hucongquan** [comment]
> Hello, i will try to reproduce your issue today, seems transfer port is not returned back to transfer ports pool.

ok，I'm looking forward to your reply.
