### ISSUE TITLE
Transferring non existing file on server side will show ControlChannel is down

### ISSUE THREAD

**Issue by juztas** [fast-data-transfer/fdt#6]
Server will get this error:
```
May 16, 2017 1:32:13 AM lia.util.net.copy.FDTWriterSession internalClose
INFO: 
The FDTWriterSession ( 01f6393d-db78-4068-b808-40d7805738bf ) finished with error(s). Cause: ControlChannel is down
java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2576)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1295)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:349)
	at lia.util.net.copy.transport.ControlChannel.run(ControlChannel.java:449)
	at java.lang.Thread.run(Thread.java:662)
```
while on client: 
```
java.lang.Exception: java.io.IOException: No such file: /home/ubuntu/dtn1.xml
	at lia.util.net.copy.FDTSessionManager.addFDTClientSession(FDTSessionManager.java:126)
	at lia.util.net.copy.FDT.<init>(FDT.java:252)
	at lia.util.net.copy.FDT.main(FDT.java:694)
Caused by: java.io.IOException: No such file: /home/ubuntu/dtn1.xml
	at lia.util.net.copy.FileReaderSession.<init>(FileReaderSession.java:38)
	at lia.util.net.copy.FileReaderSession.<init>(FileReaderSession.java:27)
	at lia.util.net.copy.FDTReaderSession.internalInit(FDTReaderSession.java:274)
	at lia.util.net.copy.FDTReaderSession.localInit(FDTReaderSession.java:159)
	at lia.util.net.copy.FDTReaderSession.<init>(FDTReaderSession.java:110)
	at lia.util.net.copy.FDTSessionManager.addFDTClientSession(FDTSessionManager.java:112)
	... 2 more
```
So server should know what was the failure and that it is not server issue.

**Comment by fixy** [comment]
Fixed in commit 771accccd635b0e53817262ef68ab26e341d4f04
