### ISSUE TITLE
FDT throws error:

### ISSUE THREAD

**Issue by audiomuze** [fast-data-transfer/fdt#72]
As of today invoking:
```java -jar ~/fdt/fdt.jar -c target_ip -P 10 -d /target/path/ -r ./*```

throws error:
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at lia.util.net.copy.FDTMain.main(FDTMain.java:55)
Caused by: java.lang.IllegalArgumentException: Illegal syntax! You can use either Client/Server (-c/-d) syntax, either SCP syntax
        at lia.util.net.common.Utils.parseArguments(Utils.java:537)
        at lia.util.net.copy.FDT.main(FDT.java:440)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 2 more
```

**Comment by audiomuze** [comment]
Seems error was related to target path.
